version: "3.0"

services:
  authentication:
    image: adomargon/node-authentication:1.0
    container_name: authentication_container
    ports:
      - "8081:80"

  playmobil:
    image: adomargon/server_playmobil:0.22
    container_name: playmobil_container
    ports:
      - "8082:80"

# sudo docker exec -it playmobil_container /bin/sh