### Chequeo que haga bien la validacion
POST http://127.0.0.1:8081/api/login_user
content-type: application/x-www-form-urlencoded

username=sonia.silverado
&password=s

#-----------------------------------

### Retrieve series success
GET http://127.0.0.1:8082/api/series
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE3MDI0NjMxMzUsImV4cCI6MTcwMjQ3NzUzNX0.Gb2vrOLpc1ya_qXIMOCcaSKuawpMQdax5HX4sxDm73c

### Retrieve boxes success
GET http://127.0.0.1:8082/api/serie/7bc17d34-6858-4b51-9ccd-7e280ec3b5be/boxes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE3MDIzOTk1NDUsImV4cCI6MTcwMjQxMzk0NX0.jiSaG1os8SflJGRdPag3buppYq59g7sRSmdGsVDwZZE

### Retrieve box by uuid success
GET http://127.0.0.1:8082/api/box/df94b9ba-d532-46fb-a3b4-7c2aacf4f770
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE3MDI0NjMxMzUsImV4cCI6MTcwMjQ3NzUzNX0.Gb2vrOLpc1ya_qXIMOCcaSKuawpMQdax5HX4sxDm73c

### Retrieve figures of box by uuid success
GET http://127.0.0.1:8082/api/box/df94b9ba-d532-46fb-a3b4-7c2aacf4f770/figures
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE3MDI0NjgwNjksImV4cCI6MTcwMjQ4MjQ2OX0.-0MkOZ4j8GPDXweiQgJizwRPrMCmX9CMFlVRQV1CxnY

### Retrieve figure by uuid success
GET http://127.0.0.1:8082/api/figure/466b422c-383a-4fef-8575-a8e68f9e563d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE3MDI0NjgwNjksImV4cCI6MTcwMjQ4MjQ2OX0.-0MkOZ4j8GPDXweiQgJizwRPrMCmX9CMFlVRQV1CxnY

### http://127.0.0.1:8082/assets/roman-soldier.jpg
