### Chequeo que haga bien la validacion
POST http://127.0.0.1:8081/api/login_user
content-type: application/x-www-form-urlencoded

username=sonia.silverado
&password=s

#-----------------------------------

### Retrieve series success
GET http://127.0.0.1:8082/api/series
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE3MDEyODE5MDksImV4cCI6MTcwMTI5NjMwOX0.vD4EvvVMuvaZhmsgrvFB7ahFqC-8xLMxQn6SV2ik0sc

### Retrieve boxes success
GET http://127.0.0.1:8082/api/serie/7bc17d34-6858-4b51-9ccd-7e280ec3b5be/boxes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE3MDEyODE5MDksImV4cCI6MTcwMTI5NjMwOX0.vD4EvvVMuvaZhmsgrvFB7ahFqC-8xLMxQn6SV2ik0sc

### Retrieve box by uuid success
GET http://127.0.0.1:8082/api/box/2969cb0a-e117-4b00-97fc-1887cbd046c0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE3MDE1Mzk2MzQsImV4cCI6MTcwMTU1NDAzNH0.bLoyskehQhnlYsGQPYejtktcjxu9iJiYV9aCYe9pKXc

### Retrieve figures of box by uuid success
GET http://127.0.0.1:8082/api/box/243308d5-6ff7-4798-8c83-9348fe1ad089/figures
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE3MDE1Mzk2MzQsImV4cCI6MTcwMTU1NDAzNH0.bLoyskehQhnlYsGQPYejtktcjxu9iJiYV9aCYe9pKXc

### Retrieve figure by uuid success
GET http://127.0.0.1:8082/api/figure/466b422c-383a-4fef-8575-a8e68f9e563d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE3MDE1Mzk2MzQsImV4cCI6MTcwMTU1NDAzNH0.bLoyskehQhnlYsGQPYejtktcjxu9iJiYV9aCYe9pKXc

### http://127.0.0.1:8082/assets/roman-soldier.jpg
